version: '2'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./.postgres/postgres-data:/var/lib/postgresql/data
    environment:
      # make sure in development, these variables match with those in
      # ./clubapp/.env.
      - POSTGRES_DB=ohsmathcc
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
