version: "2"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./.postgres/postgres-data-prod:/var/lib/postgresql/data
    environment:
      # make sure in development, these variables match with those in
      # ./clubapp/.env.
      - POSTGRES_DB=ohsmathcc
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
  web:
    depends_on:
      - db
    image: fnndsc/python-poetry
    environment:
      - POSTGRES_DB=ohsmathcc
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
