# Generated by Django 4.0.4 on 2022-05-12 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-timestamp']},
        ),
    ]
