# Generated by Django 4.0.4 on 2022-05-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_alter_registration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['timestamp']},
        ),
    ]
