# Generated by Django 4.0.4 on 2022-05-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_alter_registration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['deadline']},
        ),
    ]
