# Generated by Django 4.0.4 on 2022-05-19 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('time', models.CharField(choices=[('1', '06:00AM PST-07:15AM PST'), ('2', '07:15AM PST-08:30AM PST'), ('3', '08:30AM PST-09:45AM PST'), ('4', '09:45AM PST-11:00AM PST'), ('5', '11:00AM PST-12:15PM PST'), ('6', '12:15PM PST-01:30PM PST'), ('7', '01:30PM PST-02:45PM PST'), ('8', '02:45PM PST-04:00PM PST'), ('9', '04:00PM PST-05:15PM PST'), ('10', '05:15PM PST-06:30PM PST'), ('11', '06:30PM PST-07:45PM PST'), ('12', '07:45PM PST-09:00PM PST'), ('13', '09:00PM PST-10:15PM PST')], max_length=2)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='times.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
